version: "2"
run:
  issues-exit-code: 1
linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - ireturn
    - misspell
    - mnd
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
  settings:
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - fieldalignment
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    nestif:
      min-complexity: 15
    nolintlint:
      require-explanation: true
      require-specific: true
    tagliatelle:
      case:
        rules:
          json: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocyclo
          - gosec
          - varnamelen
        path: _test\.go
      - linters:
          - gosec
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: error strings should not be capitalized
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ayoisaiah/f2
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
